language: go
sudo: required
go:
  - 1.13.x
env:
  global:
    - GOPROXY=https://proxy.golang.org
    - GO111MODULE=on
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.13
git:
  depth: 1
before_install:
  - mkdir -p ~/.ssh
  - ls -la ~/.ssh
  - openssl aes-256-cbc -K $encrypted_6ac805c1866b_key -iv $encrypted_6ac805c1866b_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host douyacun\n\thostname ${hostname}\n\tport ${port}\n\tuser ${user}\n\tIdentityFile  ~/.ssh/id_rsa" > ~/.ssh/config
  - echo ${key} >> ~/.ssh/known_hosts
deploy:
  provider: script
  script: bash scripts/travis.sh
  skip_cleanup: true

