language: go
os: 
  - linux
before_install:
  # 初始化可能是没有~/.ssh目录
  - mkdir -p ~/.ssh
  - openssl aes-256-cbc -K $encrypted_6ac805c1866b_key -iv $encrypted_6ac805c1866b_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  # 确保权限是600
  - chmod 600 ~/.ssh/id_rsa
  # 方便使用 ssh douyacun 直接连接服务器
  - echo -e "Host douyacun\n\thostname ${hostname}\n\tport ${port}\n\tuser ${user}\n\tStrictHostKeyChecking no\n\tIdentityFile  ~/.ssh/id_rsa" > ~/.ssh/config
# 这里skip是为了避过travis默认的脚本
install: skip
script: skip
deploy:
  provider: script
  script: bash scripts/travis.sh
  cleanup: false
  on:
    tags: true